// Builds src/index.ts into dist/bloc-engine.js: one classic script that defines
// `window.BlocEngine` (TECHNICAL §122). Unminified, so a git diff of dist/ reads
// like the source change that caused it.
//
//   node build.mjs           write dist/bloc-engine.js
//   node build.mjs --check   rebuild in memory; fail if it differs from the
//                            committed file (CI, via scripts/verify-engine-build.mjs)
//
// 🚨 dist/ is COMMITTED and is what the live site serves, byte for byte. Edit
//    the source, run the build, commit both. Never hand-edit dist/.
import { build } from 'esbuild';
import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const here = dirname(fileURLToPath(import.meta.url));
const OUT = join(here, 'dist', 'bloc-engine.js');
const CHECK = process.argv.includes('--check');
// --against=<file>: compare with another file instead (the verify script's control).
const AGAINST = (process.argv.find(a => a.startsWith('--against=')) || '').slice('--against='.length) || OUT;

const result = await build({
  entryPoints: [join(here, 'src', 'index.ts')],
  bundle: true,
  format: 'iife',
  globalName: 'BlocEngine',
  target: 'es2020',
  platform: 'browser',
  charset: 'utf8',
  legalComments: 'none',
  write: false,
  logLevel: 'warning',
  banner: { js: '// GENERATED by engine/build.mjs from engine/src/ — do not edit. TECHNICAL §122.' },
});
const bytes = result.outputFiles[0].contents;

if (CHECK) {
  const committed = existsSync(AGAINST) ? readFileSync(AGAINST) : null;
  if (!committed || !Buffer.from(bytes).equals(committed)) {
    console.error('FAIL: engine/dist/bloc-engine.js is not the build of engine/src/. Run `npm run build` in engine/ and commit dist/.');
    process.exit(1);
  }
  console.log(`engine/dist/bloc-engine.js matches a fresh build (${bytes.length} bytes)`);
} else {
  writeFileSync(OUT, bytes);
  console.log(`wrote engine/dist/bloc-engine.js (${bytes.length} bytes)`);
}
