// Builds src/index.ts into dist/bloc-engine.js: one classic script that defines
// `window.BlocEngine` (TECHNICAL §122); and src/server.ts into
// dist/bloc-engine-server.mjs, an ES module for the bloc-push Edge Function
// (§156). Unminified, so a git diff of dist/ reads like the source change that
// caused it.
//
//   node build.mjs           write both files
//   node build.mjs --check   rebuild in memory; fail if either differs from its
//                            committed file (CI, via scripts/verify-engine-build.mjs)
//
// 🚨 dist/ is COMMITTED and is what the live site serves, byte for byte. Edit
//    the source, run the build, commit both. Never hand-edit dist/.
import { build } from 'esbuild';
import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const here = dirname(fileURLToPath(import.meta.url));
const OUT = join(here, 'dist', 'bloc-engine.js');
const CHECK = process.argv.includes('--check');
// --against=<file>: compare with another file instead (the verify script's control).
const AGAINST = (process.argv.find(a => a.startsWith('--against=')) || '').slice('--against='.length) || OUT;

// Two outputs from one source (§122, §156):
//   dist/bloc-engine.js          src/index.ts, a classic script defining `BlocEngine` (BLOC)
//   dist/bloc-engine-server.mjs  src/server.ts, an ES module (the bloc-push Edge Function)
const TARGETS = [
  { entry: 'index.ts', out: 'bloc-engine.js', format: 'iife', globalName: 'BlocEngine', platform: 'browser' },
  { entry: 'server.ts', out: 'bloc-engine-server.mjs', format: 'esm', platform: 'neutral' },
];

let failed = false;
for (const t of TARGETS) {
  const out = join(here, 'dist', t.out);
  const result = await build({
    entryPoints: [join(here, 'src', t.entry)],
    bundle: true,
    format: t.format,
    ...(t.globalName ? { globalName: t.globalName } : {}),
    target: 'es2020',
    platform: t.platform,
    charset: 'utf8',
    legalComments: 'none',
    write: false,
    logLevel: 'warning',
    banner: { js: '// GENERATED by engine/build.mjs from engine/src/ — do not edit. TECHNICAL §122.' },
  });
  const bytes = result.outputFiles[0].contents;
  if (CHECK) {
    // --against applies to the BLOC bundle only (the verify script's control).
    const against = t.out === 'bloc-engine.js' ? AGAINST : out;
    const committed = existsSync(against) ? readFileSync(against) : null;
    if (!committed || !Buffer.from(bytes).equals(committed)) {
      console.error(`FAIL: engine/dist/${t.out} is not the build of engine/src/. Run \`npm run build\` in engine/ and commit dist/.`);
      failed = true;
    } else {
      console.log(`engine/dist/${t.out} matches a fresh build (${bytes.length} bytes)`);
    }
  } else {
    writeFileSync(out, bytes);
    console.log(`wrote engine/dist/${t.out} (${bytes.length} bytes)`);
  }
}
if (failed) process.exit(1);
